USE [master]
GO
/****** Object:  Database [FUT]    Script Date: 12/3/2024 12:26:13 AM ******/
CREATE DATABASE [FUT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FUT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.NHATNAM2112\MSSQL\DATA\FUT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FUT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.NHATNAM2112\MSSQL\DATA\FUT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FUT] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FUT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FUT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FUT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FUT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FUT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FUT] SET ARITHABORT OFF 
GO
ALTER DATABASE [FUT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FUT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FUT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FUT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FUT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FUT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FUT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FUT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FUT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FUT] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FUT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FUT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FUT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FUT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FUT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FUT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FUT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FUT] SET RECOVERY FULL 
GO
ALTER DATABASE [FUT] SET  MULTI_USER 
GO
ALTER DATABASE [FUT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FUT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FUT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FUT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FUT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FUT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FUT', N'ON'
GO
ALTER DATABASE [FUT] SET QUERY_STORE = ON
GO
ALTER DATABASE [FUT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FUT]
GO
/****** Object:  Table [dbo].[account]    Script Date: 12/3/2024 12:26:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[account](
	[uID] [int] IDENTITY(1,1) NOT NULL,
	[fullname] [nvarchar](255) NOT NULL,
	[username] [nvarchar](255) NOT NULL,
	[password] [nvarchar](255) NOT NULL,
	[email] [nvarchar](255) NOT NULL,
	[PhoneNumber] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_account] PRIMARY KEY CLUSTERED 
(
	[uID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[category]    Script Date: 12/3/2024 12:26:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[category](
	[cid] [int] NOT NULL,
	[cname] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_category] PRIMARY KEY CLUSTERED 
(
	[cid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[order]    Script Date: 12/3/2024 12:26:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[order](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ac_id] [int] NOT NULL,
	[totalmoney] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[order_detail]    Script Date: 12/3/2024 12:26:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[order_detail](
	[pid] [int] NOT NULL,
	[cid] [int] NOT NULL,
	[name] [nvarchar](200) NOT NULL,
	[quantity] [int] NOT NULL,
	[price] [float] NOT NULL,
	[total] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[product]    Script Date: 12/3/2024 12:26:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[product](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](200) NOT NULL,
	[image] [nvarchar](200) NOT NULL,
	[price] [float] NOT NULL,
	[title] [nvarchar](200) NOT NULL,
	[description] [nvarchar](1000) NOT NULL,
	[cate_ID] [int] NOT NULL,
	[sell_ID] [int] NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [FUT] SET  READ_WRITE 
GO
