CREAT DATABASE [OJTDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OJTDB', FILENAME = N'D:\OJTDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OJTDB_log', FILENAME = N'D:\OJTDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [OJTDB] SET COMPATIBILITY_LEVEL = 150
GO


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OJTDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OJTDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OJTDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OJTDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OJTDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OJTDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [OJTDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [OJTDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OJTDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OJTDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OJTDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OJTDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OJTDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OJTDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OJTDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OJTDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [OJTDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OJTDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OJTDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OJTDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OJTDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OJTDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OJTDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OJTDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OJTDB] SET  MULTI_USER 
GO
ALTER DATABASE [OJTDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OJTDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OJTDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OJTDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OJTDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OJTDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [OJTDB] SET QUERY_STORE = OFF
GO


USE [OJTDB]
GO

/*** USER, ROLE ***/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[user_id] [INT] IDENTITY(1,1) NOT NULL,
	[username] [VARCHAR](100) NULL,
	[password] [VARCHAR](255) NULL,
	[email] [VARCHAR](255) NULL,
	[fullname] [VARCHAR](255) NULL,
	[phone_number] [VARCHAR](15) NULL,
    /*[created_at] DATETIME DEFAULT CURRENT_TIMESTAMP,
    [updated_at] DATETIME ON UPDATE CURRENT_TIMESTAMP,*/

	CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
	(
	[user_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Role](
	[user_id] [INT] NOT NULL,
	[role_id] [INT] NOT NULL,
)
GO

CREATE TABLE [dbo].[Role](					/* Student, instructor, admin */
	[role_id] [INT] IDENTITY(1,1) NOT NULL,
	[role_name] [VARCHAR](255) NULL UNIQUE,

	CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
	(
	[role_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[User_Role]  WITH CHECK  ADD CONSTRAINT [FK_UserID_Role] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([user_id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[User_Role]  WITH CHECK  ADD CONSTRAINT [FK_RoleID_Role] FOREIGN KEY([role_id])
REFERENCES [dbo].[Role] ([role_id])
ON DELETE CASCADE
GO

/*** COURSES, CATEGORIES, LECTURES (BÀI GIẢNG), ASSIGNMENT ***/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Courses](
	[course_id] [INT] IDENTITY(1,1) NOT NULL,
	[course_name]	[VARCHAR](255),
	[description] [TEXT],
    [instructor_id] [INT],
    [category_id] [INT],
    [start_date] [DATE],
    [end_date] [DATE],
    /*[created_at] DATETIME DEFAULT CURRENT_TIMESTAMP,
    [updated_at] DATETIME ON UPDATE CURRENT_TIMESTAMP,*/

	CONSTRAINT [PK_Courses] PRIMARY KEY CLUSTERED 
	(
	[course_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Categories] (
    category_id [INT] IDENTITY(1,1) NOT NULL,
    category_name [VARCHAR](255) NOT NULL UNIQUE,

	CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
	(
	[category_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Courses]  WITH CHECK  ADD CONSTRAINT [FK_CoursesCategory] FOREIGN KEY([category_id])
REFERENCES [dbo].[Categories] ([category_id])
ON DELETE CASCADE
GO

CREATE TABLE [dbo].[Enrollments] (
    [enrollment_id] [INT] IDENTITY(1,1) NOT NULL,
    [user_id] [INT],
    [course_id] [INT],
	[status_id] [INT],
    /*enrolled_at DATETIME DEFAULT CURRENT_TIMESTAMP,*/

	CONSTRAINT [PK_Enrollments] PRIMARY KEY CLUSTERED 
	(
	[enrollment_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Enrollments]  WITH CHECK  ADD CONSTRAINT [FK_EnrollCourse] FOREIGN KEY([course_id])
REFERENCES [dbo].[Courses] ([course_id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Enrollments]  WITH CHECK  ADD CONSTRAINT [FK_EnrollUser] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([user_id])
ON DELETE CASCADE
GO

CREATE TABLE [dbo].[Status](					/* Enrolled, Completed, Dropped */
	[status_id] [INT] IDENTITY(1,1) NOT NULL,
	[status_name] [VARCHAR](255) NULL UNIQUE,

	CONSTRAINT [PK_Status] PRIMARY KEY CLUSTERED 
	(
	[status_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Enrollments]  WITH CHECK  ADD CONSTRAINT [FK_EnrollStatus] FOREIGN KEY([status_id])
REFERENCES [dbo].[Status] ([status_id])
ON DELETE CASCADE
GO

CREATE TABLE [Lectures] (
    [lecture_id] [INT] IDENTITY(1,1) NOT NULL,
    [course_id] [INT],
    [title] [VARCHAR](255) NOT NULL,
    [content] [TEXT],
    [video_url] [VARCHAR](255),
    /*created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,*/

    CONSTRAINT [PK_Lectures] PRIMARY KEY CLUSTERED 
	(
	[lecture_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Lectures]  WITH CHECK  ADD CONSTRAINT [FK_LecturesCourses] FOREIGN KEY([course_id])
REFERENCES [dbo].[Courses] ([course_id])
ON DELETE CASCADE
GO

CREATE TABLE [Assignments] (
    [assignment_id] [INT] IDENTITY(1,1) NOT NULL,
    [lecture_id] [INT],
    [title] [VARCHAR](255) NOT NULL,
    [description] [TEXT],
    [due_date] [DATETIME],
    /*created_at DATETIME DEFAULT CURRENT_TIMESTAMP,*/

    CONSTRAINT [PK_Assignments] PRIMARY KEY CLUSTERED 
	(
	[assignment_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Assignments]  WITH CHECK  ADD CONSTRAINT [FK_AssignmentsLectures] FOREIGN KEY([lecture_id])
REFERENCES [dbo].[Lectures] ([lecture_id])
ON DELETE CASCADE
GO

CREATE TABLE [Submissions] (
    [submission_id] [INT] IDENTITY(1,1) NOT NULL,
    [assignment_id] [INT],
    [user_id] [INT],
    [file_path] [VARCHAR](255),
    [grade] [DECIMAL](5, 2),
    /*submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,*/
    [feedback] [TEXT],
    
	CONSTRAINT [PK_Submissions] PRIMARY KEY CLUSTERED 
	(
	[submission_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Submissions]  WITH CHECK  ADD CONSTRAINT [FK_SubmissionsAssignments] FOREIGN KEY([assignment_id])
REFERENCES [dbo].[Assignments] ([assignment_id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Submissions]  WITH CHECK  ADD CONSTRAINT [FK_SubmissionsUser] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([user_id])
ON DELETE CASCADE
GO

CREATE TABLE [CourseProgress] (
    [progress_id] [INT] IDENTITY(1,1) NOT NULL,
    [user_id] [INT],
    [course_id] [INT],
    [completed_lectures] [INT] DEFAULT 0,
    [completion_status] [INT] DEFAULT 0, /*[ENUM]('in_progress', 'completed') DEFAULT 'in_progress',*/				/* In_progress, complete */
    /*last_accessed DATETIME DEFAULT CURRENT_TIMESTAMP,*/
	
	CONSTRAINT [PK_CourseProgress] PRIMARY KEY CLUSTERED 
	(
	[progress_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CourseProgress]  WITH CHECK  ADD CONSTRAINT [FK_CourseProgressCourses] FOREIGN KEY([course_id])
REFERENCES [dbo].[Courses] ([course_id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CourseProgress]  WITH CHECK  ADD CONSTRAINT [FK_CourseProgressUser] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([user_id])
ON DELETE CASCADE
GO

/* QnA, News, Comments */
CREATE TABLE [QnA] (
    [qna_id] [INT] IDENTITY(1,1) NOT NULL,
    [course_id] [INT],
    [user_id] [INT],
    [question] [TEXT] NOT NULL,
    [answer] [TEXT],
    [created_at] [DATETIME] DEFAULT CURRENT_TIMESTAMP,
    [answered_at] [DATETIME],
    
	CONSTRAINT [PK_QnA] PRIMARY KEY CLUSTERED 
	(
	[qna_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[QnA]  WITH CHECK  ADD CONSTRAINT [FK_QnACourses] FOREIGN KEY([course_id])
REFERENCES [dbo].[Courses] ([course_id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[QnA]  WITH CHECK  ADD CONSTRAINT [FK_QnAProgressUser] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([user_id])
ON DELETE CASCADE
GO

CREATE TABLE [News] (
    [news_id] [INT] IDENTITY(1,1) NOT NULL,
    [title] [VARCHAR](255) NOT NULL,
    [content] [TEXT],
    [created_by] [INT],	
    /*created_at DATETIME DEFAULT CURRENT_TIMESTAMP,*/
	
	CONSTRAINT [PK_News] PRIMARY KEY CLUSTERED 
	(
	[news_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[News]  WITH CHECK  ADD CONSTRAINT [FK_NewsProgressUser] FOREIGN KEY([created_by])
REFERENCES [dbo].[User] ([user_id])
ON DELETE CASCADE
GO


CREATE TABLE [Comments] (
    [comment_id] [INT] IDENTITY(1,1) NOT NULL,
    [lecture_id] [INT],
    [user_id] [INT],
    [content] [TEXT] NOT NULL,
    /*[created_at] DATETIME DEFAULT CURRENT_TIMESTAMP,*/

	CONSTRAINT [PK_Comments] PRIMARY KEY CLUSTERED 
	(
	[comment_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Comments]  WITH CHECK  ADD CONSTRAINT [FK_CommentsLectures] FOREIGN KEY([lecture_id])
REFERENCES [dbo].[Lectures] ([lecture_id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Comments]  WITH CHECK  ADD CONSTRAINT [FK_CommentsUser] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([user_id])
ON DELETE CASCADE
GO
